apiVersion: v1
kind: Namespace
metadata:
  name: hook
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: test-hook
  namespace: hook
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-hook
  namespace: hook
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-hook
  template:
    metadata:
      labels:
        app: test-hook
    spec:
      serviceAccountName: test-hook
      containers:
        - name: test-hook
          image: test-hook:latest
          imagePullPolicy: Never
          env:
            - name: ALLOWED_CLIENT_SPIFFE_IDS
              value: "${CREDEX_SPIFFE_ID}"
            - name: SPIFFE_ENDPOINT_SOCKET
              value: "unix:///run/spire/sockets/spire-agent.sock"
          ports:
            - containerPort: 8443
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
          volumeMounts:
            - mountPath: /run/spire/sockets
              name: spire-agent-socket
              readOnly: true
      volumes:
        - name: spire-agent-socket
          csi:
            driver: "csi.spiffe.io"
            readOnly: true
---
apiVersion: v1
kind: Service
metadata:
  name: test-hook
  namespace: hook
spec:
  selector:
    app: test-hook
  ports:
    - port: 443
      targetPort: 8443
